[package]
name = "dechiffrust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rpassword = "7.0"
aes-gcm = "0.9"
argon2 = "0.4"
rand = "0.8"
aead = "0.5.2"
zxcvbn = "3.1.0"
